### ISSUE TITLE
library issue?

### ISSUE THREAD

**Issue by silvacarl2** [Softcatala/whisper-ctranslate2#115]
we did this: pip install --upgrade --no-cache-dir --force-reinstall git+https://github.com/Softcatala/whisper-ctranslate2

but no matter what we do, the result is this:

time whisper-ctranslate2 --model large-v2 --language en --word_timestamps True --output_format json childrenatplay_davies_ah_64kb.mp3
Detected language 'English' with probability 1.000000
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
Aborted (core dumped)

real    0m6.853s
user    0m10.305s
sys     0m3.037s

do we need to pin it to a specific version of libcudnn?

**Comment by thr3a** [comment]
I had a similar error, but I solved it by installing an older version of ctranslate2.

```
pip install ctranslate2==4.4.0
```

**Comment by FriedGenera** [comment]
> I had a similar error, but I solved it by installing an older version of ctranslate2.
> 
> ```
> pip install ctranslate2==4.4.0
> ```

Seems that new release of ctranslate uses cudnn 9 not 8 and they haven't updated the documentation on their website to reflect that. I only found out by going to their [github](https://github.com/OpenNMT/CTranslate2/releases/tag/v4.5.0)

**Comment by silvacarl2** [comment]
yes, this fixed it:

# for libcudnn8 for whisper-ctranslate2
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb && sudo apt update
sudo apt install libcudnn8 libcudnn8-dev
