### ISSUE TITLE
Unable to work with cuda

### ISSUE THREAD

**Issue by fybd88** [Softcatala/whisper-ctranslate2#95]
I installed the whisper-ctranslate2 on my laptop (system win 11). I have an RTX 4060 GPU and the GPU index is 1 (index 0 for intel built-in video card). I installed cuda toolkit 12.4.1 and cnDNN 9.1. However, it shows "RuntimeError: CUDA failed with error invalid device ordinal". How to solve this? Thank you

**Comment by fybd88** [comment]
I also tried to delete the "--device" option, it triess to work with my GPU, but ends after showing the probability of language is 1.0000, without any transcription.

**Comment by fybd88** [comment]
Solved. I forgot to install pytorch....

**Comment by FriedGenera** [comment]
> > Solved. I forgot to install pytorch....
> 
> Thanks, this solved my problem (PyTorch doesn't seem to be mentioned in the docs).
> 
I was wondering which version did you guys install?

**Comment by rollingmoai** [comment]
Sorry for the late reply. Here's what I did to get it working (using [uv](https://github.com/astral-sh/uv) on Windows):
```
uv tool install whisper-ctranslate2 -p 3.14 -w torch -w torchvision -w torchaudio --index https://download.pytorch.org/whl/cu128
```

~The `torch` package comes with cuDNN 9 (which is not supported by faster-whisper yet), so download cuDNN 8 for CUDA 12 manually for now: https://developer.nvidia.com/rdp/cudnn-archive. Extract zip and add `bin` folder to PATH~ Update: See https://github.com/Softcatala/whisper-ctranslate2/issues/95#issuecomment-2572419235

**Comment by fybd88** [comment]
many thx



发自我的iPhone


------------------ Original ------------------
From: rollingmoai ***@***.***&gt;
Date: Mon,Oct 21,2024 1:26 PM
To: Softcatala/whisper-ctranslate2 ***@***.***&gt;
Cc: fybd88 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Softcatala/whisper-ctranslate2] Unable to work with cuda (Issue#95)





 
Sorry for the late reply. Here's what I did to get it working (using pipx on Windows):
 pipx install whisper-ctranslate2 --python 3.12 pipx runpip whisper-ctranslate2 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124  
The torch package comes with cuDNN 9 (which is not supported by faster-whisper yet), so download cuDNN 8 for CUDA 12 manually for now: https://developer.nvidia.com/rdp/cudnn-archive. Extract zip and add to PATH

**Comment by FriedGenera** [comment]
> Sorry for the late reply. Here's what I did to get it working (using pipx on Windows):
> 
> ```
> pipx install whisper-ctranslate2 --python 3.12
> pipx runpip whisper-ctranslate2 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
> ```
> 
> The `torch` package comes with cuDNN 9 (which is not supported by faster-whisper yet), so download cuDNN 8 for CUDA 12 manually for now: https://developer.nvidia.com/rdp/cudnn-archive. Extract zip and add to PATH

seems to just crash for me after detecting the language
